### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by ChaunceyWoo** [SorashitaInnei/Magic-for-typecho#6]
Error establishing a database connection
数据库正确

**Comment by Innei** [comment]
只是按照typecho提供的连接数据库的方式,使用Pdo驱动连接的,刚刚想起来 你需要php7.0版本即以上.
如果你是php5.5以上你需要改驱动方式

**Comment by Innei** [comment]
![image](https://user-images.githubusercontent.com/41265413/56087628-8e338f00-5ea1-11e9-951f-00c44b883360.png)
你需要在这里改

**Comment by ChaunceyWoo** [comment]
怎么修改?

**Comment by Innei** [comment]
你可以参考你的博客根目录下的 config.inc.php 进行修改
